import{S as h,i as a}from"./assets/vendor-BrddEoy-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const g="44417625-4fee654a3e06908df7f1d6188",y="https://pixabay.com/api/";function b(i,t=1,n=51){return fetch(`${y}?key=${g}&q=${encodeURIComponent(i)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${n}`).then(o=>{if(!o.ok)throw new Error("Failed to fetch images");return o.json()}).then(o=>o).catch(o=>{throw console.error("Error fetching images:",o),o})}function L(i){const t=document.querySelector(".gallery"),n=i.map(({webformatURL:o,largeImageURL:e,tags:r,likes:s,views:p,comments:d,downloads:m})=>`
    <a href="${e}" class="gallery-item">
      <img src="${o}" alt="${r}" loading="lazy" />
      <div class="info">
        <p><b>Likes</b><br>${s}</p>
        <p><b>Views</b><br>${p}</p>
        <p><b>Comments</b><br>${d}</p>
        <p><b>Downloads</b><br>${m}</p>
      </div>
    </a>
  `).join("");t.innerHTML=n,new h(".gallery a").refresh()}function $(){document.querySelector(".gallery").innerHTML=""}const q=document.querySelector(".search-form"),v=document.querySelector(".search-input"),f=document.querySelector(".loader");let c="",l=1;function S(){f.classList.add("visible")}function u(){f.classList.remove("visible")}q.addEventListener("submit",function(i){if(i.preventDefault(),c=v.value.trim(),!c){a.error({title:"Error",message:"Please enter a search query",position:"topRight"});return}l=1,$(),S(),b(c,l).then(t=>{u(),t.hits.length===0?a.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):L(t.hits)}).catch(t=>{u(),a.error({title:"Error",message:t.message,position:"topRight"})})});
//# sourceMappingURL=index.js.map
