import{S as L,i as a}from"./assets/vendor-BrddEoy-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const v="44417625-4fee654a3e06908df7f1d6188",$="https://pixabay.com/api/";function f(i,r=1,n=15){return fetch(`${$}?key=${v}&q=${encodeURIComponent(i)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${n}`).then(o=>{if(!o.ok)throw new Error("Failed to fetch images");return o.json()}).then(o=>o).catch(o=>{throw console.error("Error fetching images:",o),o})}function d(i){const r=document.querySelector(".gallery"),n=i.map(({webformatURL:o,largeImageURL:e,tags:t,likes:s,views:g,comments:y,downloads:b})=>`
    <a href="${e}" class="gallery-item">
      <img src="${o}" alt="${t}" loading="lazy" />
      <div class="info">
        <p><b>Likes</b><br>${s}</p>
        <p><b>Views</b><br>${g}</p>
        <p><b>Comments</b><br>${y}</p>
        <p><b>Downloads</b><br>${b}</p>
      </div>
    </a>
  `).join("");r.innerHTML=n,new L(".gallery a").refresh()}function q(){document.querySelector(".gallery").innerHTML=""}const S=document.querySelector(".search-form"),E=document.querySelector(".search-input"),m=document.querySelector(".load-more"),p=document.querySelector(".loader");let c="",l=1;function h(){p.classList.add("visible")}function u(){p.classList.remove("visible")}S.addEventListener("submit",function(i){if(i.preventDefault(),c=E.value.trim(),!c){a.error({title:"Error",message:"Please enter a search query",position:"topRight"});return}l=1,q(),h(),f(c,l).then(r=>{u(),r.hits.length===0?a.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(d(r.hits),m.classList.add("visible"))}).catch(r=>{u(),a.error({title:"Error",message:r.message,position:"topRight"})})});m.addEventListener("click",function(){l+=1,h(),f(c,l).then(i=>{u(),d(i.hits)}).catch(i=>{u(),a.error({title:"Error",message:i.message,position:"topRight"})})});
//# sourceMappingURL=index.js.map
